version: "3.9"

services:
    database:
        container_name: postgres
        image: postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - ./data/db:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080